sonar.projectKey=Insaner1980_KnitTools
sonar.organization=insaner1980

sonar.sources=app/src/main/java
sonar.java.binaries=app/build/intermediates/javac/debug/classes,app/build/tmp/kotlin-classes/debug

# Exclusions
sonar.exclusions=**/build/**,**/generated/**,**/*Generated*.kt

# Duplication exclusions
sonar.cpd.exclusions=**/build/**,**/generated/**

# Coverage exclusions
sonar.coverage.exclusions=**/build/**,**/generated/**
